tests:
  - "**/*test*"

factory:
  - "**/factory*"

examples:
  - "examples/**/*"

api:
  - main.go

config:
  - config/**/*

machine:
  - machine/**/*

plugins:
  - inventoryplugins/**/*

waitron:
  - waitron/**/*

repo:
  - ./*
